# -*- mode: ruby -*-
# vi: set ft=ruby :

SHA=`git show`.split[1]

Vagrant.configure('2') do |config|
  config.vm.box      = 'base'
  config.vm.box_url  = 'https://github.com/2creatives/vagrant-centos/releases/download/v0.1.0/centos64-x86_64-20131030.box'
  config.vm.hostname = "#{ENV['USER']}-homedir"
  config.vm.provision "shell" do |s|
    s.inline = "export HOMEDIR_SHA=#{SHA} && bash /vagrant/install.sh"
  end
end
